/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/spxrwHgIGrW
 */
import { CardTitle, CardHeader, CardContent, Card } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { TableHead, TableRow, TableHeader, TableCell, TableBody, Table } from "@/components/ui/table"
import { Badge } from "@/components/ui/badge"
import Link from "next/link"
import { Avatar } from "@/components/ui/avatar"

export function Ranking() {
  return (
    (<Card className="w-full overflow-hidden rounded-lg shadow-md">
      <CardHeader className="px-4 py-3 border-b">
        <CardTitle>Ranking Table</CardTitle>
      </CardHeader>
      <CardContent>
        <Table className="min-w-full divide-y divide-gray-200">
          <TableHeader>
            <TableRow>
              <TableHead
                className="px-6 py-3 text-xs font-medium uppercase tracking-wider cursor-pointer">
                <Button variant="ghost">Rank</Button>
              </TableHead>
              <TableHead
                className="px-6 py-3 text-xs font-medium uppercase tracking-wider cursor-pointer">
                <Button variant="ghost">Name</Button>
              </TableHead>
              <TableHead
                className="px-6 py-3 text-xs font-medium uppercase tracking-wider cursor-pointer">
                <Button variant="ghost">Score</Button>
              </TableHead>
              <TableHead
                className="px-6 py-3 text-xs font-medium uppercase tracking-wider cursor-pointer">
                <Button variant="ghost">Country</Button>
              </TableHead>
            </TableRow>
          </TableHeader>
          <TableBody className="bg-white divide-y divide-gray-200">
            <TableRow>
              <TableCell className="px-6 py-4">
                <Badge>1</Badge>
              </TableCell>
              <TableCell className="px-6 py-4">
                <Link className="text-sm font-medium text-gray-900" href="#">
                  Jane Doe
                </Link>
              </TableCell>
              <TableCell className="px-6 py-4">
                <span className="text-sm text-gray-500">879</span>
              </TableCell>
              <TableCell className="px-6 py-4 text-2xl">
              🇦🇷 
              </TableCell>
            </TableRow>
          </TableBody>
        </Table>
      </CardContent>
    </Card>)
  );
}
