/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/spxrwHgIGrW
 */
import { CardTitle, CardHeader, CardContent, Card } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { TableHead, TableRow, TableHeader, TableCell, TableBody, Table } from "@/components/ui/table"
import { Badge } from "@/components/ui/badge"
import Link from "next/link"
import { Avatar } from "@/components/ui/avatar"

export function Ranking() {
  return (
    (<Card className="w-full overflow-hidden rounded-lg shadow-md">
      <CardHeader className="px-4 py-3 border-b">
        <CardTitle>Ranking Table</CardTitle>
      </CardHeader>
      <CardContent>
        <Table className="min-w-full divide-y divide-gray-200">
          <TableHeader>
            <TableRow>
              <TableHead
                className=" py-3 text-xs font-medium uppercase tracking-wider flex justify-center cursor-pointer">
                <Button variant="ghost">Top</Button>
              </TableHead>
              <TableHead
                className=" py-3 text-xs font-medium uppercase   tracking-wider cursor-pointer">
                <Button variant="ghost">Nombre</Button>
              </TableHead>
              <TableHead
                className=" py-3 text-xs font-medium uppercase text-center  tracking-wider cursor-pointer">
                <Button variant="ghost">Impresiones</Button>
              </TableHead>
              <TableHead
                className=" py-3 text-xs font-medium uppercase tracking-wider flex justify-center cursor-pointer">
                <Button variant="ghost">País</Button>
              </TableHead>
            </TableRow>
          </TableHeader>
          <TableBody className="bg-white divide-y divide-gray-200">
            <TableRow>
              <TableCell className=" text-center py-4">
                <Badge>1</Badge>
              </TableCell>
              <TableCell className=" py-4">
                <Link className="text-sm font-medium text-gray-900" href="#">
                  Jane Doe
                </Link>
              </TableCell>
              <TableCell className=" py-4 text-center">
                <span className="text-sm text-gray-500">879</span>
              </TableCell>
              <TableCell className=" py-4 text-2xl  text-center ">
🇦🇷 
              </TableCell>
            </TableRow>
          </TableBody>
        </Table>
      </CardContent>
    </Card>)
  );
}
